name: Run Go Program
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout adk-docs repo
      uses: actions/checkout@v4

    - name: Checkout adk-docs-features repo
      uses: actions/checkout@v4
      with:
        repository: 'tpryan/adk-docs-features'
        path: 'adk-docs-features'

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go mod tidy
      working-directory: ./adk-docs-features

    - name: Run program
      run: go run main.go
      working-directory: ./adk-docs-features
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
